"""
Signal 1: LLM-based classification via Groq (llama-3.3-70b-versatile).

Captures: holistic semantic and stylistic coherence -- does the text
"read" as something a human would plausibly write, given context, voice,
and internal consistency? This is a different kind of signal than the
stylometric one: it's semantic/contextual rather than purely structural.

What it can't capture: it can be fooled by AI text that has been
deliberately prompted to sound casual/human, and it can misjudge unusual
but genuine human voices (non-native speakers, neurodivergent writing
styles, translated text) as "off" and therefore AI-like. This is a known
failure mode discussed in planning.md and README.md.
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError(
                "GROQ_API_KEY is not set. Add it to your .env file (see .env.example)."
            )
        _client = Groq(api_key=api_key)
    return _client


SYSTEM_PROMPT = """You are a text provenance analyst. Given a piece of writing, assess \
whether it was most likely written by a human or generated by an AI language model.

Respond with ONLY a JSON object, no other text, in this exact format:
{
  "ai_probability": <float between 0.0 and 1.0, where 1.0 = certainly AI-generated, \
0.0 = certainly human-written>,
  "reasoning": "<one or two sentence explanation of the specific signals you noticed>"
}

Consider: naturalness of voice, specificity of detail, presence of genuine idiosyncrasy \
vs. generic phrasing, logical/structural patterns typical of LLM output (e.g. \
"it is important to note", balanced pro/con framing, hedging language), and whether the \
text reads like it came from lived experience vs. synthesized knowledge.

Be honest about uncertainty -- if the text is ambiguous, return a value near 0.5 rather \
than forcing a confident guess."""


def llm_signal(text: str) -> dict:
    """
    Calls Groq to get a holistic AI-likelihood assessment.
    Returns a dict with llm_ai_probability (float 0-1) and reasoning (str).
    Falls back to a neutral score with an error note if the API call fails,
    so the rest of the pipeline can still run.
    """
    client = _get_client()

    try:
        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.2,
            max_tokens=200,
        )
        raw = completion.choices[0].message.content.strip()

        # Models occasionally wrap JSON in code fences despite instructions.
        raw = raw.replace("```json", "").replace("```", "").strip()

        parsed = json.loads(raw)
        ai_probability = float(parsed.get("ai_probability", 0.5))
        ai_probability = max(0.0, min(1.0, ai_probability))
        reasoning = str(parsed.get("reasoning", ""))

        return {
            "llm_ai_probability": round(ai_probability, 4),
            "reasoning": reasoning,
            "error": None,
        }

    except Exception as exc:  # noqa: BLE001 -- deliberately broad: any failure degrades gracefully
        return {
            "llm_ai_probability": 0.5,
            "reasoning": "LLM signal unavailable; defaulted to neutral.",
            "error": str(exc),
        }


if __name__ == "__main__":
    sample = (
        "ok so i finally tried that new ramen place downtown and honestly? "
        "underwhelming. the broth was fine but they put WAY too much sodium in it."
    )
    print(llm_signal(sample))
